from django.views.generic.base import ContextMixin, RedirectView, TemplateResponseMixin, TemplateView, View
from django.views.generic.list import BaseListView, ListView, MultipleObjectMixin, MultipleObjectTemplateResponseMixin
from django.views.generic.detail import BaseDetailView, DetailView, SingleObjectMixin, SingleObjectTemplateResponseMixin
from django.views.generic.edit import BaseCreateView, BaseDeleteView, BaseFormView, BaseUpdateView, CreateView, DeleteView, DeletionMixin, FormMixin, FormView, ModelFormMixin, ProcessFormView, UpdateView
from django.views.generic.dates import ArchiveIndexView, BaseArchiveIndexView, BaseDateDetailView, BaseDateListView, BaseDayArchiveView, BaseMonthArchiveView, BaseTodayArchiveView, BaseWeekArchiveView, BaseYearArchiveView, DateDetailView, DateMixin, DayArchiveView, DayMixin, MonthArchiveView, MonthMixin, TodayArchiveView, WeekArchiveView, WeekMixin, YearArchiveView, YearMixin
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeDoneView, PasswordChangeView, PasswordContextMixin, PasswordResetCompleteView, PasswordResetConfirmView, PasswordResetDoneView, PasswordResetView, SuccessURLAllowedHostsMixin
from django.forms.forms import BaseForm, DeclarativeFieldsMetaclass, Form
from django.forms.models import BaseInlineFormSet, BaseModelForm, BaseModelFormSet, InlineForeignKeyField, ModelChoiceField, ModelChoiceIterator, ModelChoiceIteratorValue, ModelForm, ModelFormMetaclass, ModelFormOptions, ModelMultipleChoiceField
from rest_framework.views import APIView
from rest_framework.viewsets import GenericViewSet, ModelViewSet, ReadOnlyModelViewSet, ViewSet, ViewSetMixin
from rest_framework.fields import BooleanField, BuiltinSignatureError, CharField, ChoiceField, CreateOnlyDefault, CurrentUserDefault, DateField, DateTimeField, DecimalField, DictField, DurationField, EmailField, Field, FileField, FilePathField, FloatField, HStoreField, HiddenField, IPAddressField, ImageField, IntegerField, JSONField, ListField, ModelField, MultipleChoiceField, NullBooleanField, ReadOnlyField, RegexField, SerializerMethodField, SkipField, SlugField, TimeField, URLField, UUIDField, _UnvalidatedField, empty
from rest_framework.generics import CreateAPIView, DestroyAPIView, GenericAPIView, ListAPIView, ListCreateAPIView, RetrieveAPIView, RetrieveDestroyAPIView, RetrieveUpdateAPIView, RetrieveUpdateDestroyAPIView, UpdateAPIView
from rest_framework.serializers import BaseSerializer, HyperlinkedModelSerializer, ListSerializer, ModelSerializer, Serializer, SerializerMetaclass
from rest_framework.mixins import CreateModelMixin, DestroyModelMixin, ListModelMixin, RetrieveModelMixin, UpdateModelMixin
from rest_framework.parsers import BaseParser, DataAndFiles, FileUploadParser, FormParser, JSONParser, MultiPartParser
from rest_framework.authentication import BaseAuthentication, BasicAuthentication, CSRFCheck, RemoteUserAuthentication, SessionAuthentication, TokenAuthentication


classes_dict = {
	'ContextMixin': ContextMixin,
	'RedirectView': RedirectView,
	'TemplateResponseMixin': TemplateResponseMixin,
	'TemplateView': TemplateView,
	'View': View,
	'BaseListView': BaseListView,
	'ListView': ListView,
	'MultipleObjectMixin': MultipleObjectMixin,
	'MultipleObjectTemplateResponseMixin': MultipleObjectTemplateResponseMixin,
	'BaseDetailView': BaseDetailView,
	'DetailView': DetailView,
	'SingleObjectMixin': SingleObjectMixin,
	'SingleObjectTemplateResponseMixin': SingleObjectTemplateResponseMixin,
	'BaseCreateView': BaseCreateView,
	'BaseDeleteView': BaseDeleteView,
	'BaseFormView': BaseFormView,
	'BaseUpdateView': BaseUpdateView,
	'CreateView': CreateView,
	'DeleteView': DeleteView,
	'DeletionMixin': DeletionMixin,
	'FormMixin': FormMixin,
	'FormView': FormView,
	'ModelFormMixin': ModelFormMixin,
	'ProcessFormView': ProcessFormView,
	'UpdateView': UpdateView,
	'ArchiveIndexView': ArchiveIndexView,
	'BaseArchiveIndexView': BaseArchiveIndexView,
	'BaseDateDetailView': BaseDateDetailView,
	'BaseDateListView': BaseDateListView,
	'BaseDayArchiveView': BaseDayArchiveView,
	'BaseMonthArchiveView': BaseMonthArchiveView,
	'BaseTodayArchiveView': BaseTodayArchiveView,
	'BaseWeekArchiveView': BaseWeekArchiveView,
	'BaseYearArchiveView': BaseYearArchiveView,
	'DateDetailView': DateDetailView,
	'DateMixin': DateMixin,
	'DayArchiveView': DayArchiveView,
	'DayMixin': DayMixin,
	'MonthArchiveView': MonthArchiveView,
	'MonthMixin': MonthMixin,
	'TodayArchiveView': TodayArchiveView,
	'WeekArchiveView': WeekArchiveView,
	'WeekMixin': WeekMixin,
	'YearArchiveView': YearArchiveView,
	'YearMixin': YearMixin,
	'LoginView': LoginView,
	'LogoutView': LogoutView,
	'PasswordChangeDoneView': PasswordChangeDoneView,
	'PasswordChangeView': PasswordChangeView,
	'PasswordContextMixin': PasswordContextMixin,
	'PasswordResetCompleteView': PasswordResetCompleteView,
	'PasswordResetConfirmView': PasswordResetConfirmView,
	'PasswordResetDoneView': PasswordResetDoneView,
	'PasswordResetView': PasswordResetView,
	'SuccessURLAllowedHostsMixin': SuccessURLAllowedHostsMixin,
	'BaseForm': BaseForm,
	'DeclarativeFieldsMetaclass': DeclarativeFieldsMetaclass,
	'Form': Form,
	'BaseInlineFormSet': BaseInlineFormSet,
	'BaseModelForm': BaseModelForm,
	'BaseModelFormSet': BaseModelFormSet,
	'InlineForeignKeyField': InlineForeignKeyField,
	'ModelChoiceField': ModelChoiceField,
	'ModelChoiceIterator': ModelChoiceIterator,
	'ModelChoiceIteratorValue': ModelChoiceIteratorValue,
	'ModelForm': ModelForm,
	'ModelFormMetaclass': ModelFormMetaclass,
	'ModelFormOptions': ModelFormOptions,
	'ModelMultipleChoiceField': ModelMultipleChoiceField,
	'APIView': APIView,
	'GenericViewSet': GenericViewSet,
	'ModelViewSet': ModelViewSet,
	'ReadOnlyModelViewSet': ReadOnlyModelViewSet,
	'ViewSet': ViewSet,
	'ViewSetMixin': ViewSetMixin,
	'BooleanField': BooleanField,
	'BuiltinSignatureError': BuiltinSignatureError,
	'CharField': CharField,
	'ChoiceField': ChoiceField,
	'CreateOnlyDefault': CreateOnlyDefault,
	'CurrentUserDefault': CurrentUserDefault,
	'DateField': DateField,
	'DateTimeField': DateTimeField,
	'DecimalField': DecimalField,
	'DictField': DictField,
	'DurationField': DurationField,
	'EmailField': EmailField,
	'Field': Field,
	'FileField': FileField,
	'FilePathField': FilePathField,
	'FloatField': FloatField,
	'HStoreField': HStoreField,
	'HiddenField': HiddenField,
	'IPAddressField': IPAddressField,
	'ImageField': ImageField,
	'IntegerField': IntegerField,
	'JSONField': JSONField,
	'ListField': ListField,
	'ModelField': ModelField,
	'MultipleChoiceField': MultipleChoiceField,
	'NullBooleanField': NullBooleanField,
	'ReadOnlyField': ReadOnlyField,
	'RegexField': RegexField,
	'SerializerMethodField': SerializerMethodField,
	'SkipField': SkipField,
	'SlugField': SlugField,
	'TimeField': TimeField,
	'URLField': URLField,
	'UUIDField': UUIDField,
	'_UnvalidatedField': _UnvalidatedField,
	'empty': empty,
	'CreateAPIView': CreateAPIView,
	'DestroyAPIView': DestroyAPIView,
	'GenericAPIView': GenericAPIView,
	'ListAPIView': ListAPIView,
	'ListCreateAPIView': ListCreateAPIView,
	'RetrieveAPIView': RetrieveAPIView,
	'RetrieveDestroyAPIView': RetrieveDestroyAPIView,
	'RetrieveUpdateAPIView': RetrieveUpdateAPIView,
	'RetrieveUpdateDestroyAPIView': RetrieveUpdateDestroyAPIView,
	'UpdateAPIView': UpdateAPIView,
	'BaseSerializer': BaseSerializer,
	'HyperlinkedModelSerializer': HyperlinkedModelSerializer,
	'ListSerializer': ListSerializer,
	'ModelSerializer': ModelSerializer,
	'Serializer': Serializer,
	'SerializerMetaclass': SerializerMetaclass,
	'CreateModelMixin': CreateModelMixin,
	'DestroyModelMixin': DestroyModelMixin,
	'ListModelMixin': ListModelMixin,
	'RetrieveModelMixin': RetrieveModelMixin,
	'UpdateModelMixin': UpdateModelMixin,
	'BaseParser': BaseParser,
	'DataAndFiles': DataAndFiles,
	'FileUploadParser': FileUploadParser,
	'FormParser': FormParser,
	'JSONParser': JSONParser,
	'MultiPartParser': MultiPartParser,
	'BaseAuthentication': BaseAuthentication,
	'BasicAuthentication': BasicAuthentication,
	'CSRFCheck': CSRFCheck,
	'RemoteUserAuthentication': RemoteUserAuthentication,
	'SessionAuthentication': SessionAuthentication,
	'TokenAuthentication': TokenAuthentication,
	}

menu_dict = {'Django': {'Views generic base': ['ContextMixin', 'RedirectView', 'TemplateResponseMixin', 'TemplateView', 'View'], 'Views generic list': ['BaseListView', 'ListView', 'MultipleObjectMixin', 'MultipleObjectTemplateResponseMixin'], 'Views generic detail': ['BaseDetailView', 'DetailView', 'SingleObjectMixin', 'SingleObjectTemplateResponseMixin'], 'Views generic edit': ['BaseCreateView', 'BaseDeleteView', 'BaseFormView', 'BaseUpdateView', 'CreateView', 'DeleteView', 'DeletionMixin', 'FormMixin', 'FormView', 'ModelFormMixin', 'ProcessFormView', 'UpdateView'], 'Views generic dates': ['ArchiveIndexView', 'BaseArchiveIndexView', 'BaseDateDetailView', 'BaseDateListView', 'BaseDayArchiveView', 'BaseMonthArchiveView', 'BaseTodayArchiveView', 'BaseWeekArchiveView', 'BaseYearArchiveView', 'DateDetailView', 'DateMixin', 'DayArchiveView', 'DayMixin', 'MonthArchiveView', 'MonthMixin', 'TodayArchiveView', 'WeekArchiveView', 'WeekMixin', 'YearArchiveView', 'YearMixin'], 'Contrib auth views': ['LoginView', 'LogoutView', 'PasswordChangeDoneView', 'PasswordChangeView', 'PasswordContextMixin', 'PasswordResetCompleteView', 'PasswordResetConfirmView', 'PasswordResetDoneView', 'PasswordResetView', 'SuccessURLAllowedHostsMixin'], 'Forms forms': ['BaseForm', 'DeclarativeFieldsMetaclass', 'Form'], 'Forms models': ['BaseInlineFormSet', 'BaseModelForm', 'BaseModelFormSet', 'InlineForeignKeyField', 'ModelChoiceField', 'ModelChoiceIterator', 'ModelChoiceIteratorValue', 'ModelForm', 'ModelFormMetaclass', 'ModelFormOptions', 'ModelMultipleChoiceField']}, 'Rest framework': {'Views': ['APIView'], 'Viewsets': ['GenericViewSet', 'ModelViewSet', 'ReadOnlyModelViewSet', 'ViewSet', 'ViewSetMixin'], 'Fields': ['BooleanField', 'BuiltinSignatureError', 'CharField', 'ChoiceField', 'CreateOnlyDefault', 'CurrentUserDefault', 'DateField', 'DateTimeField', 'DecimalField', 'DictField', 'DurationField', 'EmailField', 'Field', 'FileField', 'FilePathField', 'FloatField', 'HStoreField', 'HiddenField', 'IPAddressField', 'ImageField', 'IntegerField', 'JSONField', 'ListField', 'ModelField', 'MultipleChoiceField', 'NullBooleanField', 'ReadOnlyField', 'RegexField', 'SerializerMethodField', 'SkipField', 'SlugField', 'TimeField', 'URLField', 'UUIDField', '_UnvalidatedField', 'empty'], 'Generics': ['CreateAPIView', 'DestroyAPIView', 'GenericAPIView', 'ListAPIView', 'ListCreateAPIView', 'RetrieveAPIView', 'RetrieveDestroyAPIView', 'RetrieveUpdateAPIView', 'RetrieveUpdateDestroyAPIView', 'UpdateAPIView'], 'Serializers': ['BaseSerializer', 'HyperlinkedModelSerializer', 'ListSerializer', 'ModelSerializer', 'Serializer', 'SerializerMetaclass'], 'Mixins': ['CreateModelMixin', 'DestroyModelMixin', 'ListModelMixin', 'RetrieveModelMixin', 'UpdateModelMixin'], 'Parsers': ['BaseParser', 'DataAndFiles', 'FileUploadParser', 'FormParser', 'JSONParser', 'MultiPartParser'], 'Authentication': ['BaseAuthentication', 'BasicAuthentication', 'CSRFCheck', 'RemoteUserAuthentication', 'SessionAuthentication', 'TokenAuthentication']}}
